import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useQuery, gql } from "@apollo/client";

const BLOGS = gql`
  {
    blogs {
      id
      text
    }
  }
`;

export default function Home() {
  const { data, error, loading } = useQuery(BLOGS);
  console.log({ data, error, loading });

  if (loading) return "Loading...";
  if (error) return <div>Some error occured while fetching data</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data.blogs.map((blog) => (
          <div>
            <h1>{blog.text}</h1>
          </div>
        ))}
      </main>
    </div>
  );
}
